local t = os.clock()
local src = game:HttpGet("loadstring(game:HttpGet("https://raw.githubusercontent.com/lordnikky/test/refs/heads/main/test.lua"))()", true)
local t2 = os.clock()
local f = loadstring(src)
local t3 = os.clock()
f()
local t4 = os.clock()
print("http: " .. math.floor((t2-t)*1000) .. "ms | loadstring(compile+deserialize): " .. math.floor((t3-t2)*1000) .. "ms | run: " .. math.floor((t4-t3)*1000) .. "ms")
